### ISSUE TITLE
Trailing slash on void elements has no effect and interacts badly with unquoted attribute values.

### ISSUE THREAD

**Issue by Kuan-Lun** [smarr/latex-to-html5#9]
In HTML, the `meta`, `br`, and `img` tags are classified as void elements, which means they only require a start tag _without corresponding end tags_. For more information, refer to the [HTML documentation](https://www.w3.org/TR/2011/WD-html-markup-20110113/syntax.html#void-element). Also, note that there are [errors on several lines](https://validator.w3.org/nu/?doc=https%3A%2F%2Fstefan-marr.de%2Fpapers%2Fpldi-marr-et-al-zero-overhead-metaprogramming%2F) in the example file [Zero-Overhead Metaprogramming](https://stefan-marr.de/papers/pldi-marr-et-al-zero-overhead-metaprogramming/).

**Comment by smarr** [comment]
Dear @Kuan-Lun, could you show me where specifically `meta`, `br`, and `img` tags have an end element? I can't see any such occurrences.

I also don't see errors in the Nu HTML Checker. I only see style info and warnings, neither of cause the HTML to be invalid.

Thank you

**Comment by Kuan-Lun** [comment]
In line 32, the code is written as `<meta name="twitter:card" content="summary" />`, but it should be `<meta name="twitter:card" content="summary">`.  Perhaps I shouldn't call it an error, but it doesn't meet the requirements.

**Comment by smarr** [comment]
This isn't an end tag. The `/` is optional and allowed.

**Comment by Kuan-Lun** [comment]
I apologize, you were right. It was my oversight.

**Comment by smarr** [comment]
No worries. Thanks for considering opening an issue!
